### ISSUE TITLE
See how the SIC/SIE changes from day to day

### ISSUE THREAD

**Issue by SooluThomas** [NOAA-HES-Capstone/icedyno#35]

**Comment by BGory** [comment]
Once we determine a specific region, we need to be concerned of lake ice. It has the same identification `3` as sea ice. We need to be sure when determining the sea-ice edges, we do not include coordinates of lake ice.

**Comment by BGory** [comment]
The MASIE HDF5 dataset are still giving issues. The x and y values are the same. This is a problem when trying to reduce the image by longitude and latitude. The IMS can be reduced to longitude and latitude. The resulting array then is updated for sea ice/no sea ice. Those values can be plotted and viewed. Those arrays can be used to count overall sea-ice values and begin with edge detection.
